### PR TITLE
Add middleware enabled HTML handler

### PR DESCRIPTION
**Pull request by SamHennessy**
An idea to allow for user-level session management

* Added CreateHTMLHandlerWithMiddleware to demo how middleware could be used
* A couple of bug fixes

Example usage here: https://github.com/SamHennessy/golive-example

### CODE REVIEW

**Comment by SamHennessy** [comment]
Sorry, added another commit by mistake. If it's too much I'd be happy to split.

**Comment by brendonferreira** [comment]
Oh man, that is super smart. Took me a moment to get my head round it but that is really great. Amazing stuff

**Comment by brendonferreira** [comment]
What is your view on passing the service using context? Maybe an anti pattern thing?
```go
app.Get("/", liveServer.CreateHTMLHandlerWithMiddleware(
		components.NewHome,
		livePage,
		middleware.Session,
		middleware.Service(ds)))
```

**Comment by SamHennessy** [comment]
@brendonferreira yes that's considered an anti-pattern in Go. The intent of context is to pass request specific data. But the line gets blurred ar some point. In this case, the service doesn't change between requests so can be pass as an argument on instantiation. A good example is the Request ID (e.g. HTTP header X-Request-ID), this is a good candidate to add in the context as will change on every request. But, it's also good to have the request-id in the logs and easy to miss. A solution is to have an instance of your logger that will automatically add the request-id on each log. In this case, it's okay to pass the logger via the context as it's different on each request.

**Comment by brendonferreira** [comment]
Thank you for clarifying that!

**Pull request merged**
